name: "ibm_hr_attrition_dbt"
version: "1.0.0"
config-version: 2

profile: "ibm_hr_attrition"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ibm_hr_attrition_dbt:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: analytics
